### ISSUE TITLE
Can't search on yggtorrent anymore

### ISSUE THREAD

**Issue by pokapow** [juliensalinas/torrengo#14]
```
An error occured during search on Ygg Torrent
ERRO[0008] The ygg search goroutine broke                _source="torrengo/torrengo.go:498" error="error while fetching url: status code error: 503 503 Service Unavailable" input=pokemon
No result found...
exit status 1

```

I think this is due to their new browser detector when searching.
Is there a way around this?

**Comment by juliensalinas** [comment]
@pokapow I have the same problem too indeed. I'm working on it!

**Comment by pokapow** [comment]
In python I use selenium webdriver with Gecko to enable javascript and bypass cloudflare. It's working fine, but I don't know how to manage this in Go.

**Comment by juliensalinas** [comment]
Yes actually in the past I used to use the [Python Clouflare Scrape](https://github.com/Anorov/cloudflare-scrape) lib which worked great but as it required Python + Nodejs I ended up using a Go lib which was much better (no external dep and much faster).
Now I'm considering going back to the Python solution as I can't seem to find a working Go solution (for the moment).

**Comment by juliensalinas** [comment]
@pokapow I finally fixed the Ygg issue. I had to completely rewrite the code in order to use Google Chrome under the hood.
It makes the program a slightly slower and sadly it requires an external dependency, but that's the best way I found to bypass the Cloudflare protection. Hopefully it will keep working for a long while!

Feel free to let me know if it's not working on your end.

**Comment by ferdir** [comment]
Hi @juliensalinas and thanks for your work ! Everything was working fine with yggtorrent until now (`No result found...`) ; it seems to be because of the Cloudflare protection again. Do you have an idea how to fix it ?

**Comment by juliensalinas** [comment]
IHi @ferdir thanks for the feedback, I'll have a look when I have a moment

**Comment by juliensalinas** [comment]
@ferdir I don't have any issue with ygg... Maybe it was a temporary problem on their server?

**Comment by ferdir** [comment]
Indeed there is no more problem
