### ISSUE TITLE
Failed installation 

### ISSUE THREAD

**Issue by Laquais** [juliensalinas/torrengo#17]
Hello,

Throws this error : 

laquais-> go get github.com/juliensalinas/torrengo
.# github.com/chromedp/chromedp
pkg/mod/github.com/chromedp/chromedp@v0.5.3/chromedp.go:155:15: assignment mismatch: 2 variables but action.Do returns 1 values

What can I do ?

Regards.

**Comment by juliensalinas** [comment]
Hi, it must be the same issue as this one: https://github.com/juliensalinas/torrengo/issues/16
Can you try to reinstall with `go get -u` and see if it works?

**Comment by Laquais** [comment]
Thank you
