### ISSUE TITLE
Failed installation with go get -u

### ISSUE THREAD

**Issue by lorenzocasbarra** [juliensalinas/torrengo#19]
$ go get -u github.com/juliensalinas/torrengo
Returns:
# github.com/chromedp/chromedp
go/pkg/mod/github.com/chromedp/chromedp@v0.7.8/query.go:1139:8: assignment mismatch: 7 variables but css.GetMatchedStylesForNode(nodes[0].NodeID).Do returns 8 values

**Comment by juliensalinas** [comment]
Thanks, let me have a look.

**Comment by juliensalinas** [comment]
It seems it was caused by an issue with the ChromeDP lib: https://github.com/chromedp/chromedp/issues/1031

I pushed a fix. Can you check if it's working now on your end @lorenzocasbarra ?

**Comment by juliensalinas** [comment]
PS: I updated the installation instructions.
I recommend that you use the following: `go install github.com/juliensalinas/torrengo@latest` (make sure you're using a recent version of Go).

Let me know if it's still broken on your end.
