### ISSUE TITLE
Feature request: transmission support

### ISSUE THREAD

**Issue by oblitum** [juliensalinas/torrengo#3]
Hi, nice tool. I'm just trying it in place of torrench, since the author vanished from the web for some months already. First thing I miss is no ability to send torrent to transmission. It would be great to have ;-)

**Comment by mikeboiko** [comment]
Yes, I would also love this feature! I could write some code for this and do a PR if you're interested.

**Comment by eschizoid** [comment]
@oblitum @mikeboiko I think I have implemented that functionality here, perhaps it helps:

https://github.com/eschizoid/flixctl/blob/master/torrent/service.go#L180

**Comment by juliensalinas** [comment]
Hello guys, I just added Transmission and QBittorrent as 2 new possible client torrents. Hope it helps!

**Comment by mikeboiko** [comment]
nice, you the man!

**Comment by oblitum** [comment]
@juliensalinas I see a reference to "transmission-gtk" in the sources, but transmission server doesn't need a gui client, I actually use a terminal one and don't have transmission-gtk in my machine. Is that relevant? Otherwise just ignore the concern. Although, I'm not using torrengo anymore, currently using a new [torrench](https://github.com/astewartau/torrench).
