### ISSUE TITLE
Printing the best results at bottom

### ISSUE THREAD

**Issue by snippins** [juliensalinas/torrengo#5]
As the first few search results are usually the best, I find myself almost always scroll up to get the torrent index.
Thus it would be nice to have an option to reverse the result table. What do you think about it, would you accept a PR for this option?

This is basically mean changing the following line of "torrengo.go" 

`renderedTorrents = append(renderedTorrents, renderedTorrent)`

to

`renderedTorrents = append([][]string{renderedTorrent}, renderedTorrents...)`

Thanks.

**Comment by juliensalinas** [comment]
Great suggestion @snippins, I just made the change.
