### ISSUE TITLE
Feature request: webtorrent support

### ISSUE THREAD

**Issue by clemlatz** [juliensalinas/torrengo#8]
I'd love to have [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) support.

Downloads are started with the `webtorrent download <torrent-id>` where `<torrent-id>` can be:
  * a magnet uri
  * a http url to .torrent file
  * a filesystem path to .torrent file
  * an info hash (hex string)

I have never done any go, but the torrengo source code seems fairly easy to understand, so I though I might have a go (haha!) as a first dive into the language and try a pull request next week if you're ok.

**Comment by juliensalinas** [comment]
If webtorrent is behaving the way you describe it might be an easy one.
You'd need to add the new `webtorrent download` command here: https://github.com/juliensalinas/torrengo/blob/609e11d10000281d805aa6fec12e93284a70fd5d/torrengo.go#L592
and add a new option in the user interface, or maybe simply remove all other options if you don't need them: https://github.com/juliensalinas/torrengo/blob/609e11d10000281d805aa6fec12e93284a70fd5d/torrengo.go#L570

Enjoy your first Go program then! :)
